// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"time"

	"github.com/google/uuid"
)

type DoodleMeeting struct {
	MeetingID     uuid.UUID
	CreatorUserID uuid.UUID
	TimeslotID    uuid.UUID
	Status        string
	StartAt       time.Time
	EndAt         time.Time
	CreatedAt     time.Time
}

type DoodleMeetingParticipant struct {
	UserID    uuid.UUID
	MeetingID uuid.UUID
}

type DoodleTimeslot struct {
	TimeslotID uuid.UUID
	UserID     uuid.UUID
	StartAt    time.Time
	EndAt      time.Time
	Status     string
	CreatedAt  time.Time
}

type DoodleUser struct {
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
}
