// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"time"

	"github.com/google/uuid"
)

type DoodleMeeting struct {
	MeetingID   uuid.UUID
	TimeslotID  uuid.UUID
	Title       string
	Description string
	Url         string
	CreatedAt   time.Time
}

type DoodleMeetingParticipant struct {
	MeetingID     uuid.UUID
	AttendeeEmail string
}

type DoodleTimeslot struct {
	TimeslotID   uuid.UUID
	UserID       uuid.UUID
	StartAt      time.Time
	EndAt        time.Time
	DurationMins int32
	CreatedAt    time.Time
}

type DoodleUser struct {
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
}
