// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO doodle.users (user_id, name)
VALUES ($1, $2)
RETURNING user_id, name, created_at
`

type CreateUserParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (DoodleUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.UserID, arg.Name)
	var i DoodleUser
	err := row.Scan(&i.UserID, &i.Name, &i.CreatedAt)
	return i, err
}
