// Package storage is the data-access layer for the corti service. Queries are
// defined in internal/storage/sql/queries and generated by sqlc (the *.gen.go
// files); this file adds the transaction wrapper and the domain-facing methods
package storage

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// ErrNotFound is returned when a row does not exist
var ErrNotFound = errors.New("not found")

// Store wraps the sqlc-generated Queries with a connection pool so it can run
// both pooled queries (q) and multi-statement transactions (withTx).
type Store struct {
	*Queries
	pool *pgxpool.Pool
}

func NewStore(pool *pgxpool.Pool) *Store {
	return &Store{Queries: New(pool), pool: pool}
}

// withTx runs fn against a transaction-bound Queries, committing on success and
// rolling back on error or panic.
func (s *Store) withTx(ctx context.Context, fn func(q *Queries) error) error {
	tx, err := s.pool.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.ReadCommitted})
	if err != nil {
		return err
	}
	defer tx.Rollback(context.WithoutCancel(ctx))

	if err := fn(s.Queries.WithTx(tx)); err != nil {
		return err
	}
	return tx.Commit(ctx)
}
